version: 1.8.0-dev-{build}

image:
  - Ubuntu
  - Visual Studio 2019

build: false

# restrict to branches
branches:
  only:
    - master
    - develop

environment:
  INTEGRATION_TEST: false
  WINDOWS_TEST: false

  # setup tests matrix
  matrix:
    - PYTHON: "3.7"
    - PYTHON: "3.8"
    - PYTHON: "3.9"
    - PYTHON: "3.10"
    - PYTHON: "3.11"
      INTEGRATION_TEST: true
      WINDOWS_TEST: true

for:
  - matrix:
      only:
        - image: Ubuntu

    cache:
      # enable cache for Python dependencies
      - "$HOME/.cache/pip"

    init:
      # load virtual env
      - "source $HOME/venv$PYTHON/bin/activate"

      # check current python version
      - "python --version"

    install:
      # install system dependencies if requested
      - "if $INTEGRATION_TEST; then sudo apt-get -qq update; fi"
      - "if $INTEGRATION_TEST; then sudo apt-get -q install -y vlc mpv; fi"

      # the features used in setup.cfg require a recent enough version of setuptools
      - "python -m pip install --upgrade \"setuptools>=46.4.0\""

      # install dependencies for test
      - "python -m pip install -e \".[tests]\""

      # check dependencies version if requested
      - "if $INTEGRATION_TEST; then vlc --version; fi"
      - "if $INTEGRATION_TEST; then mpv --version; fi"

    test_script:
      # run tests
      - "if $INTEGRATION_TEST; then python -m pytest -v --cov-report term; else python -m pytest -v --cov-report term tests/unit; fi"

      # run commands
      - "python -m dakara_player --version"
      - "dakara-player --version"

      # run code formatting tests
      - "python -m isort . --check"
      - "python -m black . --check"
      - "python -m flake8"

    after_test:
      # upload coverage stats to codecov.io
      # codecov token is stored in appveyor settings
      - "python -m codecov"

  - matrix:
      only:
        - image: Visual Studio 2019
          WINDOWS_TEST: true

    cache:
      # enable cache for Python dependencies
      - "%LOCALAPPDATA%\\pip\\Cache"

    init:
      # check current python version
      - "py -%PYTHON% --version"

    install:
      # install system dependencies if requested
      - "if %INTEGRATION_TEST% == true (cinst vlc)"
      - "if %INTEGRATION_TEST% == true (cinst mpv)"

      # the features used in setup.cfg require a recent enough version of setuptools
      - "py -%PYTHON% -m pip install --upgrade \"setuptools>=46.4.0\""

      # install dependencies for test
      - "py -%PYTHON% -m pip install -e \".[tests]\""

      # refresh console
      - "refreshenv"

    test_script:
      # run tests
      - "if %INTEGRATION_TEST% == true (py -%PYTHON% -m pytest -v --cov-report term) else (py -%PYTHON% -m pytest -v --cov-report term tests/unit)"

      # run commands
      - "py -%PYTHON% -m dakara_player --version"

      # run code formatting tests
      - "py -%PYTHON% -m isort . --check"
      - "py -%PYTHON% -m black . --check"
      - "py -%PYTHON% -m flake8"

    after_test:
      # upload coverage stats to codecov.io
      # codecov token is stored in appveyor settings
      - "py -%PYTHON% -m codecov"
