version: 1.7.0-dev-{build}

build: false

# restrict to branches
branches:
  only:
  - develop
  - master

# enable cache for Python dependencies
cache:
  - "%LOCALAPPDATA%\\pip\\Cache"

environment:
  # setup special environment variable for Appveyor CI test environment
  # it is used to disable some tests that can be harmful in this context
  APPVEYOR_CI_ENV: 1

  # setup tests matrix
  matrix:
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

# check current python version
init:
  - "py -%PYTHON_VERSION% --version"

# command to install system and python dependencies
install:
  # install system dependencies
  - "cinst vlc"

  # the features used in setup.cfg require at decent version of setuptools
  - "py -%PYTHON_VERSION% -m pip install --upgrade \"setuptools>=40.0\""

  # install dependencies for test
  - "py -%PYTHON_VERSION% -m pip install -e \".[tests]\""

# command to run tests
test_script:
  # run tests
  - "py -%PYTHON_VERSION% -m coverage run setup.py test"

  # run commands
  - "py -%PYTHON_VERSION% -m dakara_player_vlc --version"
  - "%PYTHON%\\Scripts\\dakara-play-vlc.exe --version"

  # run code formatting tests
  - "if NOT %PYTHON_VERSION% == 3.5 (py -%PYTHON_VERSION% -m  black . --check)"
  - "py -%PYTHON_VERSION% -m flake8"

# commands to manage tests results
after_test:
  # show coverage stats
  - "py -%PYTHON_VERSION% -m coverage report -m"

  # upload coverage stats to codecov.io
  # coverage must be called manually
  # codecov token is stored in appveyor settings
  - "py -%PYTHON_VERSION% -m coverage xml"
  - "py -%PYTHON_VERSION% -m codecov -X gcov --file coverage.xml"
