version: 1.7.0-{build}

image:
  - Ubuntu
  - Visual Studio 2019

build: false

# restrict to branches
branches:
  only:
    - master
    - develop

environment:
  # setup tests matrix
  matrix:
    - PYTHON: "3.6"
      INTEGRATION_TEST: false
    - PYTHON: "3.7"
      INTEGRATION_TEST: false
    - PYTHON: "3.8"
      INTEGRATION_TEST: false
    - PYTHON: "3.9"
      INTEGRATION_TEST: true

for:
  - matrix:
      only:
        - image: Ubuntu

    cache:
      # enable cache for Python dependencies
      - "$HOME/.cache/pip"

    init:
      # load virtual env
      - "source $HOME/venv$PYTHON/bin/activate"

      # check current python version
      - "python --version"

    install:
      # install system dependencies if requested
      - "if $INTEGRATION_TEST; then sudo apt-get -qq update; fi"
      - "if $INTEGRATION_TEST; then sudo apt-get install -y vlc mpv; fi"

      # the features used in setup.cfg require a recent enough version of setuptools
      - "python -m pip install --upgrade \"setuptools>=40.0\""

      # install dependencies for test
      - "python -m pip install -e \".[tests]\""

      # check dependencies version if requested
      - "if $INTEGRATION_TEST; then vlc --version; fi"
      - "if $INTEGRATION_TEST; then mpv --version; fi"

    test_script:
      # run tests
      - "if $INTEGRATION_TEST; then python -m coverage run -m pytest -v; else python -m coverage run -m pytest -v tests/unit; fi"

      # run commands
      - "python -m dakara_player --version"
      - "dakara-play --version"

      # run code formatting tests
      - "python -m black . --check"
      - "python -m flake8"

    after_test:
      # show coverage stats
      - "python -m coverage report -m"

      # upload coverage stats to codecov.io
      # codecov token is stored in appveyor settings
      - "python -m coverage xml"
      - "python -m codecov -X gcov --file coverage.xml"

  - matrix:
      only:
        - image: Visual Studio 2019

    cache:
      # enable cache for Python dependencies
      - "%LOCALAPPDATA%\\pip\\Cache"

    init:
      # check current python version
      - "py -%PYTHON% --version"

    install:
      # install system dependencies if requested
      - "if %INTEGRATION_TEST% == true (cinst vlc --force --version=3.0.12)"
      - "if %INTEGRATION_TEST% == true (cinst mpv)"

      # the features used in setup.cfg require a recent enough version of setuptools
      - "py -%PYTHON% -m pip install --upgrade \"setuptools>=40.0\""

      # install dependencies for test
      - "py -%PYTHON% -m pip install -e \".[tests]\""

      # refresh console
      - "refreshenv"

    test_script:
      # run tests
      - "if %INTEGRATION_TEST% == true (py -%PYTHON% -m coverage run -m pytest -v) else (py -%PYTHON% -m coverage run -m pytest -v tests/unit)"

      # run commands
      - "py -%PYTHON% -m dakara_player --version"

      # run code formatting tests
      - "py -%PYTHON% -m black . --check"
      - "py -%PYTHON% -m flake8"

    after_test:
      # show coverage stats
      - "py -%PYTHON% -m coverage report -m"

      # upload coverage stats to codecov.io
      # codecov token is stored in appveyor settings
      - "py -%PYTHON% -m coverage xml"
      - "py -%PYTHON% -m codecov -X gcov --file coverage.xml"
