language: python
python:
  - "3.5"
  - "3.6"

# select Ubuntu version
dist: bionic

# enable cache for Python dependencies
cache: pip

# restrict to branches
branches:
  only:
    - master
    - develop

# commands to install system dependencies
before_install:
  # install system dependencies
  - sudo apt-get -qq update
  - sudo apt-get install -y vlc mpv

  # check dependencies version
  - vlc --version

# command to install python dependencies
install:
  # the features used in setup.cfg require at decent version of setuptools
  - python -m pip install --upgrade "setuptools>=40.0"

  # install dependencies for test
  - python -m pip install -e ".[tests]"

  # install module for execution tests
  - python setup.py install

# command to run tests
script:
  # run tests
  - python -m coverage run setup.py test

  # run commands
  - python -m dakara_player_vlc --version
  - dakara-play-vlc --version

  # run code formatting tests
  - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then black . --check; fi
  - flake8

# commands to manage tests results
after_script:
  # show coverage stats
  - python -m coverage report -m

  # upload coverage stats to codecov.io
  # codecov token is stored in travis settings
  - python -m codecov -X gcov
