build: false

environment:
    matrix:
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.3"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "curl.exe -fsS -o vlc.msi http://download.videolan.org/pub/videolan/vlc/last/win64/vlc-3.0.3-win64.msi"
  - "msiexec.exe /i vlc.msi /quiet"
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"

test_script:
  - "%PYTHON%/python.exe ./tests.py -v"
