build: false

environment:
    matrix:
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.3"
      PYTHON_ARCH: "64"

init:
  - "echo %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "cinst vlc"
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"

test_script:
  - "start /b %PYTHON%/python.exe ./tests.py -v"
  - "%PYTHON%/Scripts/flake8.exe"
